name: Test evo-setup-action

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:
  gha-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - name: Checkout Git repository
      uses: actions/checkout@v3

    - name: Set up Evo runtime
      uses: evo-lua/evo-setup-action@main
      with:
        version: 'v0.0.3'

    - name: Run Lua script
      run: |
        evo .github/hello-world.lua
      shell: bash
